# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# by me version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
# by me jobs:
  # by me say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    # by me docker:
      # by me - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    # by me steps:
      # by me - checkout
      # by me - run:
        # by me  name: "Say hello"
        # by me  command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
# by me workflows: 
  # by me say-hello-workflow:
    # by me jobs:
      # by me - say-hello


version: 2.1
jobs: 
  build:
    docker:
      #- image:  cimg/node:16.20.1-browsers
      - image:  circleci/node:16
    steps:
      - checkout
      # - run:
      #     name: installing Google Chrome
      #     command: |
      #       wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #       sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      #       sudo apt-get update
      #       sudo apt-get install google-chrome-stable --allow-unauthenticated
      - run:
          name: installing automation framework
          command: |
            npm install --save
      - run:
          name: running tests
          command: |
            npm run wdio
workflows:
  build_tests:
    jobs:
      - build
